#!/usr/bin/env bash

# Possible formats:
# (t|b|bug_|task_|)1234((_|)_short_description|)

function die {
  if [[ $1 ]]; then
    echo $1 >&2
  else
    echo "Usage: $0 [-l|--link|-o|--open]" >&2
  fi
  exit 1
}

function get_url {
  url_pattern=`git config --get sanity.tasksurl`
  [[ $url_pattern =~ "<>" ]] || die "bad tasks url format"
  url=${url_pattern/<>/$task_number}
}

[[ $# < 2 ]] || die

current_branch=`git-current-branch`

[[ $current_branch =~ ^(t|b|bug_|task_)?([0-9]+) ]]
task_number="${BASH_REMATCH[2]}"

if [[ $task_number -eq "" ]]; then
  die "No task number detected"
elif [[ $# == 1 ]]; then
  get_url
  if [[ $1 == "-l" ]] || [[ $1 == "--link" ]]; then
    echo $url
  elif [[ $1 == "-o" ]] || [[ $1 == "--open" ]]; then
    if hash local-open 2>/dev/null; then
      open_cmd=`which local-open`
    elif hash xdg-open 2>/dev/null; then
      open_cmd=`which xdg-open`
    else
      open_cmd=`which open`
    fi

    $open_cmd $url
  else
    die
  fi
else
  echo $task_number
fi

