#!/usr/bin/env bash

# Appends the current bugtracker task ID (or link, if sanity.taskurl is specified in your git config)
# to the end of your commit messages.
#
# To use, rename this file to 'prepare-commit-msg' and place it in your .git/hooks directory.
#
# Depends on: git-task

if [[ `git task --link 2>/dev/null` ]]; then
  task_line="`git task --link`"
elif [[ `git task 2>/dev/null` ]]; then
  task_line="Task `git task`"
fi

if [[ $task_line ]]; then
  if [[ $2 == "" ]]; then
    perl -pi -e "print \"\n\n\".'${task_line}' if $. == 1" $1
  else
    echo -e "\n$task_line" >> $1
  fi
fi
